-- Leave Management System - initial schema

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(150) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('EMPLOYEE', 'MANAGER', 'HR'))
);

CREATE TABLE teams (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    manager_id  BIGINT,
    CONSTRAINT uk_teams_name UNIQUE (name)
);

CREATE TABLE employees (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    employee_code VARCHAR(20)  NOT NULL,
    full_name     VARCHAR(120) NOT NULL,
    job_title     VARCHAR(100),
    joining_date  DATE         NOT NULL,
    team_id       BIGINT,
    manager_id    BIGINT,
    CONSTRAINT uk_employees_user UNIQUE (user_id),
    CONSTRAINT uk_employees_code UNIQUE (employee_code),
    CONSTRAINT fk_employees_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_employees_team FOREIGN KEY (team_id) REFERENCES teams (id),
    CONSTRAINT fk_employees_manager FOREIGN KEY (manager_id) REFERENCES employees (id),
    CONSTRAINT ck_employees_not_own_manager CHECK (manager_id IS NULL OR manager_id <> id)
);
CREATE INDEX ix_employees_team ON employees (team_id);
CREATE INDEX ix_employees_manager ON employees (manager_id);

ALTER TABLE teams
    ADD CONSTRAINT fk_teams_manager FOREIGN KEY (manager_id) REFERENCES employees (id);
CREATE INDEX ix_teams_manager ON teams (manager_id);

CREATE TABLE leave_types (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(30)  NOT NULL,
    name        VARCHAR(60)  NOT NULL,
    description VARCHAR(255),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_leave_types_code UNIQUE (code)
);

CREATE TABLE leave_policies (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_type_id      BIGINT       NOT NULL,
    annual_entitlement NUMERIC(5, 1) NOT NULL,
    prorated           BOOLEAN      NOT NULL DEFAULT TRUE,
    count_weekends     BOOLEAN      NOT NULL DEFAULT FALSE,
    count_holidays     BOOLEAN      NOT NULL DEFAULT FALSE,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_leave_policies_type UNIQUE (leave_type_id),
    CONSTRAINT fk_leave_policies_type FOREIGN KEY (leave_type_id) REFERENCES leave_types (id),
    CONSTRAINT ck_leave_policies_entitlement CHECK (annual_entitlement >= 0 AND annual_entitlement <= 365)
);

CREATE TABLE workflow_settings (
    id                             BIGINT PRIMARY KEY,
    escalation_timeout_minutes     INTEGER      NOT NULL,
    team_absence_threshold_percent NUMERIC(5, 2) NOT NULL,
    updated_at                     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_workflow_settings_singleton CHECK (id = 1),
    CONSTRAINT ck_workflow_settings_timeout CHECK (escalation_timeout_minutes > 0),
    CONSTRAINT ck_workflow_settings_threshold CHECK (team_absence_threshold_percent > 0 AND team_absence_threshold_percent <= 100)
);

CREATE TABLE holidays (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    holiday_date DATE         NOT NULL,
    CONSTRAINT uk_holidays_date UNIQUE (holiday_date)
);

CREATE TABLE leave_balances (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id        BIGINT        NOT NULL,
    leave_type_id      BIGINT        NOT NULL,
    balance_year       INTEGER       NOT NULL,
    annual_entitlement NUMERIC(5, 1) NOT NULL,
    allocated          NUMERIC(5, 1) NOT NULL,
    used               NUMERIC(5, 1) NOT NULL DEFAULT 0,
    pending            NUMERIC(5, 1) NOT NULL DEFAULT 0,
    version            BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uk_leave_balances_employee_type_year UNIQUE (employee_id, leave_type_id, balance_year),
    CONSTRAINT fk_leave_balances_employee FOREIGN KEY (employee_id) REFERENCES employees (id),
    CONSTRAINT fk_leave_balances_type FOREIGN KEY (leave_type_id) REFERENCES leave_types (id),
    CONSTRAINT ck_leave_balances_non_negative CHECK (allocated >= 0 AND used >= 0 AND pending >= 0)
);

CREATE TABLE leave_requests (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id          BIGINT       NOT NULL,
    leave_type_id        BIGINT       NOT NULL,
    approver_id          BIGINT       NOT NULL,
    start_date           DATE         NOT NULL,
    end_date             DATE         NOT NULL,
    days                 INTEGER      NOT NULL,
    reason               VARCHAR(500) NOT NULL,
    status               VARCHAR(30)  NOT NULL,
    team_absence_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
    team_leave_warning   BOOLEAN      NOT NULL DEFAULT FALSE,
    has_team_conflict    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    escalated_at         TIMESTAMP WITH TIME ZONE,
    version              BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT fk_leave_requests_employee FOREIGN KEY (employee_id) REFERENCES employees (id),
    CONSTRAINT fk_leave_requests_type FOREIGN KEY (leave_type_id) REFERENCES leave_types (id),
    CONSTRAINT fk_leave_requests_approver FOREIGN KEY (approver_id) REFERENCES employees (id),
    CONSTRAINT ck_leave_requests_dates CHECK (end_date >= start_date),
    CONSTRAINT ck_leave_requests_days CHECK (days > 0),
    CONSTRAINT ck_leave_requests_status CHECK (status IN
        ('PENDING_MANAGER', 'PENDING_HR', 'APPROVED', 'REJECTED', 'ESCALATED', 'CANCEL_REQUESTED', 'CANCELLED'))
);
CREATE INDEX ix_leave_requests_employee_status ON leave_requests (employee_id, status);
CREATE INDEX ix_leave_requests_approver_status ON leave_requests (approver_id, status);
CREATE INDEX ix_leave_requests_status_created ON leave_requests (status, created_at);
CREATE INDEX ix_leave_requests_dates ON leave_requests (start_date, end_date);

CREATE TABLE audit_logs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_request_id BIGINT,
    actor_id         BIGINT,
    actor_name       VARCHAR(120) NOT NULL,
    actor_role       VARCHAR(20)  NOT NULL,
    action           VARCHAR(40)  NOT NULL,
    previous_status  VARCHAR(30),
    new_status       VARCHAR(30),
    comment          VARCHAR(1000),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_audit_logs_request FOREIGN KEY (leave_request_id) REFERENCES leave_requests (id),
    CONSTRAINT fk_audit_logs_actor FOREIGN KEY (actor_id) REFERENCES employees (id)
);
CREATE INDEX ix_audit_logs_request ON audit_logs (leave_request_id, created_at);
CREATE INDEX ix_audit_logs_created ON audit_logs (created_at);
-- A request can only ever be escalated once; guards the scheduler against duplicate escalation records.
CREATE UNIQUE INDEX uk_audit_logs_single_escalation ON audit_logs (leave_request_id) WHERE action = 'ESCALATED';

CREATE TABLE notifications (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id     BIGINT        NOT NULL,
    type             VARCHAR(40)   NOT NULL,
    title            VARCHAR(150)  NOT NULL,
    message          VARCHAR(1000) NOT NULL,
    leave_request_id BIGINT,
    is_read          BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES users (id),
    CONSTRAINT fk_notifications_request FOREIGN KEY (leave_request_id) REFERENCES leave_requests (id)
);
CREATE INDEX ix_notifications_recipient ON notifications (recipient_id, is_read, created_at);
