package com.accentra.leavemanagement.enums;

public enum AuditAction {
    CREATED,
    MANAGER_APPROVED,
    MANAGER_REJECTED,
    HR_APPROVED,
    HR_REJECTED,
    ESCALATED,
    WITHDRAWN,
    CANCELLATION_REQUESTED,
    CANCELLATION_APPROVED,
    CANCELLATION_REJECTED,
    BALANCE_UPDATED,
    POLICY_CREATED,
    POLICY_UPDATED,
    SETTINGS_UPDATED,
    HOLIDAY_ADDED,
    HOLIDAY_REMOVED
}
