package com.accentra.leavemanagement.enums;

public enum NotificationType {
    LEAVE_SUBMITTED,
    NEW_LEAVE_REQUEST,
    TEAM_CONFLICT_WARNING,
    MANAGER_APPROVED,
    HR_APPROVED,
    LEAVE_REJECTED,
    AWAITING_HR_APPROVAL,
    LEAVE_ESCALATED,
    LEAVE_WITHDRAWN,
    CANCELLATION_REQUESTED,
    CANCELLATION_APPROVED,
    CANCELLATION_REJECTED
}
